version: '3.3'
services:
    proxy:
        image: jwilder/nginx-proxy:alpine
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
        container_name: nginx-proxy
        networks:
            nextcloud_network:
                ipv4_address: 172.28.0.2
            le_network:
                ipv4_address: 172.29.0.2
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./proxy/conf.d:/etc/nginx/conf.d:rw
            - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
            - ./proxy/html:/usr/share/nginx/html:rw
            - ./proxy/certs:/etc/nginx/certs:ro
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: unless-stopped
    
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        depends_on:
            - proxy
        networks:
            le_network:
                ipv4_address: 172.29.0.3
        volumes:
            - ./proxy/certs:/etc/nginx/certs:rw
            - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
            - ./proxy/html:/usr/share/nginx/html:rw
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
    
    redis:
        image: bitnami/redis:latest
        container_name: redis-cache
        networks:
            nextcloud_network:
                ipv4_address: 172.28.0.5
        env_file: .env
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - ALLOW_EMPTY_PASSWORD=no
        restart: unless-stopped

    ncdb:
        image: mariadb:latest
        container_name: nc-mariadb
        networks:
            nextcloud_network:
                ipv4_address: 172.28.0.4
        env_file: .env
        volumes:
            - ncdb:/var/ib/mysql
            - /etc/localtime:/etc/localtime:ro
        environment: 
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=nextcloud
        restart: unless-stopped

    ncapp:
        image: nextcloud:latest
        container_name: nc-app
        networks:
            nextcloud_network:
                ipv4_address: 172.28.0.3
        ports:
            - 80
        depends_on:
            - proxy
            - ncdb
        env_file: .env
        volumes:
            - nextcloud:/var/www/html
            - ./ncapp/config:/var/www/html/config
            - ./ncapp/custom_apps:/var/www/html/custom_apps
            - ./ncapp/data:/var/www/html/data
            - ./ncapp/themes:/var/www/html/themes
            - /etc/localtime:/etc/localtime:ro
        environment:
            - NEXTCLOUD_TRUSTED_DOMAINS=${VIRTUAL_HOST}
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - LETSENCRYPT_HOST=${VIRTUAL_HOST}
            - LETSENCRYPT_EMAIL=${LE_MAIL}
        restart: unless-stopped

networks:
    nextcloud_network:
        external: true
    le_network:
        external: true

volumes:
    ncdb:
    nextcloud:

